package com.balmon.SpringMvcHbXml.model;

// Generated 25-dic-2014 20:31:18 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal matricula;
	private String nombre;
	private String app;
	private String apm;
	private BigDecimal edad;
	private String sexo;
	private Date fechaRegistro;
	private String usuario;

	public Alumnos() {
	}

	public Alumnos(BigDecimal matricula, String nombre, String app, String apm,
			BigDecimal edad, String sexo, Date fechaRegistro, String usuario) {
		this.matricula = matricula;
		this.nombre = nombre;
		this.app = app;
		this.apm = apm;
		this.edad = edad;
		this.sexo = sexo;
		this.fechaRegistro = fechaRegistro;
		this.usuario = usuario;
	}

	public BigDecimal getMatricula() {
		return this.matricula;
	}

	public void setMatricula(BigDecimal matricula) {
		this.matricula = matricula;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApp() {
		return this.app;
	}

	public void setApp(String app) {
		this.app = app;
	}

	public String getApm() {
		return this.apm;
	}

	public void setApm(String apm) {
		this.apm = apm;
	}

	public BigDecimal getEdad() {
		return this.edad;
	}

	public void setEdad(BigDecimal edad) {
		this.edad = edad;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

}
